[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
perp_amm = "GG2jR83szT5N1jTyVPC2dUC8Yzfg3R77Sn1U7ugDtnoN"
perp_margin_accounts = "EZKKGMsZbG3fwUa61XFeBYdYqpuLnKMPyZqNo1nyeSU9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

# The cluster from which I am cloning the accounts
[test.validator]
url = "https://api.devnet.solana.com"

# The external programs I want to deploy
[[test.genesis]]
address = "HEvSKofvBgfaexv23kMabbYqxasxU3mQ4ibBMEmJWHny"
program = "target/deploy/chainlink.so"

# Addresses that I want to clone (e.g. price feed account from chainlink or pyth)
[[test.validator.clone]]
address = "99B2bTijsU6f1GCT73HmdR7HCFFjGMBcPZY6jZ96ynrR"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
ammtest = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/amm-*.ts"
margintest = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/margin-*.ts"
